### ISSUE TITLE
TypeError when adding SVG to Dialog

### ISSUE THREAD

**Issue by Loahrs** [vaadin-component-factory/svg#10]
Hello, I hope this is the right place to report an issue I encountered.

**What's happening?**
A TypeError is thrown when trying to open a VaadinDialog that contains a Svg. The Dialog is not displayed due to this. 

**How to reproduce?**
Create a class extending Dialog and create and add a Svg Element to this. 
I created a minimal example from the Vaadin Gitpod Starter: 
https://gitpod.io#snapshot/52dc9674-0f2e-4445-85d2-89e8d4b49d7c

**More Info**
- I think the error occures when the following line of code is executed client side:
vcf-svg.js

```
  get children() {
    return this.draw.children();
  }
```

- This only happens when the dialog is supposed to directly show the svg. I created another dialog that works fine, where a user needs to make a selection first and only after that the Svg is added (when the dialog is already open and displayed on the client side).

**Comment by Frettman** [comment]
I'm experiencing the same thing.

**Comment by jcgueriaud1** [comment]
It should be fixed in v1.1.1. Just released today
