### ISSUE TITLE
Not working with Vaadin 23

### ISSUE THREAD

**Issue by TatuLund** [vaadin-component-factory/svg#18]
See: https://stackoverflow.com/questions/75628911/how-to-add-a-column-with-an-svg-containing-a-circle-element-to-a-vaadin-grid-i

**Comment by jcgueriaud1** [comment]
There is updated vcf-svg component for Vaadin 23 (23.1.0) https://github.com/vaadin-component-factory/vcf-svg
But the Java component seems to use an older version

**Comment by djarnis73** [comment]
Any chance you will make this work with Vaadin 23/24 anytime soon? I would love to contribute with a PR but I'm completely oblivious to the javascript integration part. If someone can give me a hint on what needs to be done, I will give it a try.

**Comment by krissvaa** [comment]
As of version [v1.2.0](https://github.com/vaadin-component-factory/svg/releases/tag/v1.2.0) SVG component supports Vaadin Flow V23
