### ISSUE TITLE
Feature request: add tooltip support to SvgElement's

### ISSUE THREAD

**Issue by netsrotr** [vaadin-component-factory/svg#23]
In SVG each element can have a child element named `title` with an ID. The content of this element specifies any non-empty text that will be displayed by browsers as the tooltip of that element (or group of elements).

The construction using underlying svgjs 3.2 is described here: [title element](https://svgjs.dev/docs/3.2/shape-elements/#element-words).

**Comment by paodb** [comment]
Released in version 2.0.0
