### ISSUE TITLE
Feature request: add a click listener

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin-component-factory/svg#3]
From the add-on comments, since there are listener for Start and End Dragging, Could there be a way to add Click or Double-click Event Listener?

**Comment by jcgueriaud1** [comment]
@niiyeboah do you have any idea if it's possible to add the event to the component?

**Comment by niiyeboah** [comment]
@jcgueriaud1 yes it should not be hard to add those events. There is one thing though, if it is required, I think it needs a little work to get the "dblclick" to not fire a "click" event as well

**Comment by CoderGarm** [comment]
Moin alltogether,

I'm using vaadin-SVG in my corona-is-boring-project and I have a demand for a click event, too.
The java-stuff to add a click listener was not as hard and the java-script was even not as hard as i thought (I'm not the front-end guy), but I have a problem.

The XHR-event which is sended by clicking an svg element did not contain the ```data```-array which holds the ```event.detail.handler.el.node``` information like the elements ID and this stuff.

My problem is, that the data are present in the event but they are not part of the "xhr message to server" - in the screen on the left "my" click event message in comparion to the vaadin dragStartEvent message.

My "solution" is mainly a clone of the ```DragStartEventListener``` chain in java and in the javascript the same for the ```DragHandler``` chain. 
So it's basically the same code which produces different results and I cannot figure out why. So if you feel good to give some guidiance to a backend dev in the frontend world, it would be great ;)

I would like to contribute "my" solution and not only leeching stuff from other guys, if you want.
And I know too, that this problem description is kind of inexpressive.

Best Regards

![Bildschirmfoto von 2021-04-30 19-13-42](https://user-images.githubusercontent.com/76734109/116730978-6f04ed00-a9e9-11eb-8bd1-8d00aba36967.png)

**Comment by axelIkama** [comment]
A click-event listener would help me a lot as well! Any updates on this issue??

**Comment by mathieu-fanduel** [comment]
I have tried to implement this here  #13  and I managed to implement it for the Svg class but not for the SvgElement one 

and do not not were to start as this is my first contribution to a Vaadin component

**Comment by jcgueriaud1** [comment]
I'll check this week.

**Comment by jcgueriaud1** [comment]
I released a new version of the component v1.1.0 in the directory. Can you check if it's working ?

**Comment by mathieu-fanduel** [comment]
It is working 👍
